# Site settings
title: Samsir
email: # "samsiralamsamsiralam@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://samsiral.am" # the base hostname & protocol for your site
author: Samsir
name: Samsir
 
# Site logo
logo: /assets/images/brand.svg

# Select your active Socials Links.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/socials.yml
socials-links:
#  rss: true
  email: "samsiralamsamsiralam@gmail.com"
#  github: samsir
  linkedin: samsiralam
#  medium: samsir
  spotify: samsiralam
#  telephone: +62
#  yelp: yourname

# Permalinks
permalink:  pretty

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style:     :compressed # You might prefer to minify using expanded

# Use the following plug-ins
plugins:
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - LICENSE
  - README.md
  - CNAME
