# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Samsir
email: # "samsiralamsamsiralam@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://samsiralam.com" # the base hostname & protocol for your site
author: Samsir
name: Samsir
 
# Site logo
logo: /assets/images/samsiralamcom.svg

# Select your active Socials Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/socials.yml
socials-links:
#  rss: true
  email: "samsiralamsamsiralam@gmail.com"
#  facebook: username
  github: samsiralam0
#  google-plus: username
#  instagram: samsiralam0
  linkedin: samsiralam
#  medium: @samsir
#  reddit: username
#  stackoverflow: "1234567/username"
#  snapchat: username
#  spotify: yourname
#  steam: username
#  telephone: +62
#  twitch: yourname
#  twitter: samsiralam0
#  xing: yourname
#  yelp: yourname
#  youtube: yourname

# Pagination
paginate: 5
paginate_path: "/staff/page:num/"

# Excerpt
excerpt_separator: "<!-- more -->"

# Permalinks
permalink: /staff/:year/:month/:day/:title/

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style:     :compressed # You might prefer to minify using expanded

# Set Google Analytics Code
# google_analytics: UA-42261351-1

# Enter your Disqus shortname (not your username) to enable commenting on posts
disqus:

# Set Chrome tab theme color
chrome-tab-theme-color: "#14ac6c"

# Use the following plug-ins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude these files from your production _site
exclude:
  - Gemfile
  - LICENSE
  - README.md
  - CNAME
